name: Docker Build

on:
  push:
    branches: master
    paths-ignore:
      - 'images/**'
      - 'sample/**'
      - 'tests/**'
      - '**.md'
  pull_request:
    branches: master
    paths-ignore:
      - 'images/**'
      - 'sample/**'
      - 'tests/**'
      - '**.md'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: tedder42/petnet-feeder-service:latest
          
      - name: Build and push ARMv7
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: tedder42/petnet-feeder-service:latest-arm7, tedder42/petnet-feeder-service:latest-pib2
          
      - name: Build and push ARMv6
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          tags: tedder42/petnet-feeder-service:latest-arm6, tedder42/petnet-feeder-service:latest-pizero
